[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
RAILWAY_RUN_UID = "0"

# Configuration du volume persistant pour les uploads
[[volume]]
name = "uploads-volume"
mountPath = "/app/public/uploads"
